#[cfg(test)]
mod tests;

mod app;

pub use app::{
    APPLICATION_SVC, APPLICATION_SVC_FACTORY, APP_BOOTSTRAP_SVC, APP_BOOTSTRAP_SVC_FACTORY,
    APP_RUNTIME_SVC, APP_RUNTIME_SVC_FACTORY, APP_SERVICE_PROVIDER_SVC,
    APP_SERVICE_PROVIDER_SVC_FACTORY,
};
