# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[advisories]
db-path = "$CARGO_HOME/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db/raw/main/db.json.tar.gz"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"

[licenses]
unlicensed = "deny"
copyleft = "warn"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
]

[bans]
multiple-versions = "deny"
wildcards = "allow"
